# Generated by Django 3.1.2 on 2021-04-11 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_sell_sellproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='cart',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
