# Generated by Django 3.1.2 on 2021-04-11 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210411_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sell',
            name='supplier',
        ),
        migrations.AddField(
            model_name='sellproduct',
            name='supplier',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.supplier'),
        ),
        migrations.RemoveField(
            model_name='client',
            name='cart',
        ),
        migrations.AddField(
            model_name='client',
            name='cart',
            field=models.ManyToManyField(to='main.SellProduct'),
        ),
    ]
