# Generated by Django 3.1.2 on 2021-04-08 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210407_0720'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('comida', 'comida'), ('computador', 'computador'), ('livro', 'livro'), ('roupa', 'roupa'), ('movel', 'movel'), ('outros', 'outros')], default='comida', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(),
        ),
    ]
