# Generated by Django 3.1.2 on 2021-04-11 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210411_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellproduct',
            name='conclude',
            field=models.BooleanField(default=0),
        ),
    ]
