# Generated by Django 3.1.2 on 2021-04-11 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_sellproduct_conclude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellproduct',
            name='conclude',
        ),
        migrations.AddField(
            model_name='sell',
            name='conclude',
            field=models.BooleanField(default=0),
        ),
    ]
