# Generated by Django 3.1.2 on 2021-04-11 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210411_2018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='cart',
        ),
    ]
