# Generated by Django 3.1.2 on 2021-04-11 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_client_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sell',
            name='products',
        ),
        migrations.AddField(
            model_name='sellproduct',
            name='sell',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.sell'),
        ),
    ]
