# Generated by Django 3.1.4 on 2021-04-08 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210408_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(),
        ),
    ]
