# Generated by Django 3.1.2 on 2021-04-11 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210411_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellproduct',
            name='value',
            field=models.FloatField(default=0),
        ),
    ]
