# Generated by Django 3.1.2 on 2021-04-13 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_sell_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellproduct',
            name='real_value',
            field=models.FloatField(default=0),
        ),
    ]
