# Generated by Django 3.1.2 on 2021-04-04 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210404_0039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=100)),
                ('razao', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.BigIntegerField(default=0)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='User',
            new_name='Cliente',
        ),
    ]
