# Generated by Django 3.1.4 on 2021-04-04 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20210404_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='complement',
            field=models.CharField(default='', max_length=100),
        ),
    ]
