# Generated by Django 3.1.4 on 2021-04-04 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20210404_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.address'),
        ),
    ]
