# Generated by Django 3.1.4 on 2021-04-04 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='address',
        ),
    ]
